name: ink_date
description: Ink date project
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  cached_network_image: ^3.3.0
  camera: ^0.10.5+4
  connectivity_plus: ^4.0.2
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.3.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.0
  flutter_svg: ^2.0.7
  freeze: ^1.0.0
  go_router: ^10.2.0
  image_picker: ^1.0.4
  lottie: ^2.6.0
  riverpod: ^2.4.0
  secure_storage_local_storage_inspector: ^0.7.0
  shared_preferences: ^2.2.1
  slang: ^3.23.0
  slang_flutter: ^3.23.0
  table_calendar: ^3.0.5

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  lints: ^2.1.1
  slang_build_runner: ^3.23.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/config/
    - assets/fonts/
    - assets/animations/
    - assets/images/
    - assets/i18n/

  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700
