// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIU_SSnFsQUEKTAcnat9Lt--yBUPHHnrY',
    appId: '1:685651927679:web:b5d200c2d8051da0d9d54a',
    messagingSenderId: '685651927679',
    projectId: 'ink-date-9adc7',
    authDomain: 'ink-date-9adc7.firebaseapp.com',
    storageBucket: 'ink-date-9adc7.appspot.com',
    measurementId: 'G-5BDY8T0EHV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGzlSLWkm-4w7P80yIrn9WP1zgbQ57vOg',
    appId: '1:685651927679:android:e6b8b16932e32523d9d54a',
    messagingSenderId: '685651927679',
    projectId: 'ink-date-9adc7',
    storageBucket: 'ink-date-9adc7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7LSZdvJHtpFgIlmFZ7ZJRguO5acHYsBk',
    appId: '1:685651927679:ios:2e70335e937d0620d9d54a',
    messagingSenderId: '685651927679',
    projectId: 'ink-date-9adc7',
    storageBucket: 'ink-date-9adc7.appspot.com',
    iosBundleId: 'com.example.inkDate',
  );
}
